### ISSUE TITLE
Using with vanilla Promises

### ISSUE THREAD

**Issue by subblue** [charto/cwait#3]
I was wondering if there was an example on how to use this with the standard ES6 promises since they don't have a `Promise.map` function?

Thanks

**Comment by jjrv** [comment]
The purpose of this library is to limit concurrency by wrapping whatever promise-returning function you have in a `queue.wrap()` call. Without `Promise.map` it takes a bit more code just to get anything to happen concurrently.

Here's a simple example:

``` JavaScript
var cwait = require('cwait');

var queue = new cwait.TaskQueue(Promise, 1);

function delay() {
    return(new Promise(function(resolve, reject) {
        setTimeout(function() {
            console.log('Beep');
            resolve();
        }, 1000);
    }));
}

var delay2 = queue.wrap(delay);

delay();
delay();
delay();

delay2();
delay2();
delay2();
```

That runs at least on Node.js 6.0.0 using the built-in promises. It prints "Beep" 4 times after a 1-second delay (the 3 unwrapped delay calls, and the first wrapped delay call) and then 2 more times with additional 1-second delays (because the queue allows only one concurrent promise-returning function).

**Comment by subblue** [comment]
Thanks for the example, that helps :)
