### ISSUE TITLE
What if the `download` function is somehow async recursive?

### ISSUE THREAD

**Issue by xieranmaya** [charto/cwait#5]
``` js
function download (toPath) {
  if (x) {
    return new Promise()
  } else {
    return download(toPath + '(1)')
  }
}
```

**Comment by jjrv** [comment]
What this does depends on the details. Most likely your function would be like `downloadList(list)` that returns a promise resolving when everything is done. Then `queue.wrap` would limit simultaneous `downloadList` executions. If they internally make sequential downloads, this probably ends up doing what you wanted. If internally they start all downloads at the same time, you'd need to `queue.wrap` also the recursive call inside `downloadList` (ideally in a different queue, because the `downloadList` promise won't resolve until all is done).

**Comment by jjrv** [comment]
Closing this for now. If you run into some scenario that causes problems, please post it here. I'll reopen the issue and try to fix it.

**Comment by jjrv** [comment]
Now I probably understood your question. There's a new `unblock` method and a section in the readme about recursion:

https://github.com/charto/cwait#recursion

Hopefully this answers your question.
